#!/bin/bash
# ---------------------------------------------------------------------------
# CMMC Cloud Compliance Scanner — Local Development Setup
#
# Creates a Python virtual environment, installs dependencies, initializes
# the local SQLite database, and prints instructions for starting the
# development server.
#
# Usage:
#   chmod +x scripts/setup.sh
#   ./scripts/setup.sh
# ---------------------------------------------------------------------------

set -euo pipefail

# Colors for terminal output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${PROJECT_ROOT}/.venv"
BACKEND_DIR="${PROJECT_ROOT}/backend"
REQUIREMENTS="${BACKEND_DIR}/requirements.txt"

echo -e "${CYAN}=============================================${NC}"
echo -e "${CYAN}  CMMC Cloud Compliance Scanner — Setup${NC}"
echo -e "${CYAN}=============================================${NC}"
echo ""

# ---------------------------------------------------------------------------
# 1. Check prerequisites
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[1/5] Checking prerequisites...${NC}"

# Python 3.12+ required
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: python3 is not installed or not in PATH.${NC}"
    echo "       Install Python 3.12+ from https://www.python.org/downloads/"
    exit 1
fi

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PYTHON_MAJOR=$(echo "${PYTHON_VERSION}" | cut -d. -f1)
PYTHON_MINOR=$(echo "${PYTHON_VERSION}" | cut -d. -f2)

if [ "${PYTHON_MAJOR}" -lt 3 ] || { [ "${PYTHON_MAJOR}" -eq 3 ] && [ "${PYTHON_MINOR}" -lt 12 ]; }; then
    echo -e "${RED}ERROR: Python 3.12+ required. Found: ${PYTHON_VERSION}${NC}"
    exit 1
fi

echo -e "  Python version: ${GREEN}${PYTHON_VERSION}${NC}"

# Check requirements file exists
if [ ! -f "${REQUIREMENTS}" ]; then
    echo -e "${RED}ERROR: ${REQUIREMENTS} not found.${NC}"
    echo "       Run this script from the project root directory."
    exit 1
fi

echo -e "  Requirements file: ${GREEN}found${NC}"
echo ""

# ---------------------------------------------------------------------------
# 2. Create virtual environment
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[2/5] Setting up virtual environment...${NC}"

if [ -d "${VENV_DIR}" ]; then
    echo -e "  Virtual environment already exists at ${VENV_DIR}"
    echo -e "  ${YELLOW}Reusing existing environment.${NC} Delete .venv/ to recreate."
else
    python3 -m venv "${VENV_DIR}"
    echo -e "  Created virtual environment at ${GREEN}${VENV_DIR}${NC}"
fi

# Activate the virtual environment
# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"
echo -e "  Activated virtual environment"
echo ""

# ---------------------------------------------------------------------------
# 3. Install dependencies
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[3/5] Installing backend dependencies...${NC}"

pip install --upgrade pip --quiet
pip install -r "${REQUIREMENTS}" --quiet

echo -e "  ${GREEN}Dependencies installed successfully${NC}"
echo ""

# ---------------------------------------------------------------------------
# 4. Initialize local database
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[4/5] Initializing local database...${NC}"

cd "${BACKEND_DIR}"
python3 -c "
from app.db.database import engine, Base
from app.models.schemas import *
Base.metadata.create_all(bind=engine)
print('  Database tables created.')
"
cd "${PROJECT_ROOT}"

echo -e "  ${GREEN}Database initialized (SQLite: backend/cmmc_scanner.db)${NC}"
echo ""

# ---------------------------------------------------------------------------
# 5. Create .env file if it does not exist
# ---------------------------------------------------------------------------
echo -e "${YELLOW}[5/5] Checking environment configuration...${NC}"

ENV_FILE="${PROJECT_ROOT}/.env"
if [ ! -f "${ENV_FILE}" ]; then
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    ENCRYPTION_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    cat > "${ENV_FILE}" << EOF
# CMMC Scanner — Local Development Environment
# Generated by scripts/setup.sh — DO NOT commit this file

ENVIRONMENT=dev
DATABASE_URL=sqlite:///./cmmc_scanner.db
SECRET_KEY=${SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Uncomment and set for PostgreSQL:
# DATABASE_URL=postgresql://cmmc_admin:password@localhost:5432/cmmc_scanner
EOF
    echo -e "  ${GREEN}Created .env file with generated secrets${NC}"
else
    echo -e "  .env file already exists — ${YELLOW}skipping${NC}"
fi

echo ""

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo -e "${CYAN}=============================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${CYAN}=============================================${NC}"
echo ""
echo "  To start the development server:"
echo ""
echo -e "    ${CYAN}source .venv/bin/activate${NC}"
echo -e "    ${CYAN}cd backend${NC}"
echo -e "    ${CYAN}uvicorn app.main:app --reload --port 8000${NC}"
echo ""
echo "  Then open ${GREEN}http://localhost:8000${NC} in your browser."
echo ""
echo "  API docs available at:"
echo -e "    ${GREEN}http://localhost:8000/api/docs${NC}   (Swagger UI)"
echo -e "    ${GREEN}http://localhost:8000/api/redoc${NC}  (ReDoc)"
echo ""
